# Generated by Django 5.1.4 on 2025-01-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='friedly_name',
            new_name='friendly_name',
        ),
    ]
